STATES = [
  ['Acre', 'AC'],
  ['Alagoas', 'AL'],
  ['Amazonas', 'AM'],
  ['Amapá', 'AP'],
  ['Bahia', 'BA'],
  ['Ceará', 'CE'],
  ['Distrito Federal', 'DF'],
  ['Espírito Santo', 'ES'],
  ['Goiás', 'GO'],
  ['Maranhão', 'MA'],
  ['Minas Gerais', 'MG'],
  ['Mato Grosso do Sul', 'MS'],
  ['Mato Grosso', 'MT'],
  ['Pará', 'PA'],
  ['Paraíba', 'PB'],
  ['Pernambuco', 'PE'],
  ['Piauí', 'PI'],
  ['Paraná', 'PR'],
  ['Rio de Janeiro', 'RJ'],
  ['Rio Grande do Norte', 'RN'],
  ['Rondônia', 'RO'],
  ['Roraima', 'RR'],
  ['Rio Grande do Sul', 'RS'],
  ['Santa Catarina', 'SC'],
  ['Sergipe', 'SE'],
  ['São Paulo', 'SP'],
  ['Tocantins', 'TO']
]

STATES_REGIONS = {
  'AC' => 'Norte',
  'AL' => 'Nordeste',
  'AM' => 'Norte',
  'AP' => 'Norte',
  'BA' => 'Nordeste',
  'CE' => 'Nordeste',
  'DF' => 'Centro-oeste',
  'ES' => 'Sudeste',
  'GO' => 'Centro-oeste',
  'MA' => 'Nordeste',
  'MG' => 'Sudeste',
  'MS' => 'Centro-oeste',
  'MT' => 'Centro-oeste',
  'PA' => 'Norte',
  'PB' => 'Nordeste',
  'PE' => 'Nordeste',
  'PI' => 'Nordeste',
  'PR' => 'Sul',
  'RJ' => 'Sudeste',
  'RN' => 'Nordeste',
  'RO' => 'Norte',
  'RR' => 'Norte',
  'RS' => 'Sul',
  'SC' => 'Sul',
  'SE' => 'Nordeste',
  'SP' => 'Sudeste',
  'TO' => 'Norte',
}
